
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
from tkinter import *
from tkinter import ttk
from datetime import date
# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()
# Variables for Vehicle record inserition
vlDate=StringVar()
vlTime=StringVar()
vlNum=StringVar()
vlInout=StringVar()
vlOwner=StringVar()
vlMob=StringVar()
vlType=StringVar()
vlReason=StringVar()
# End

# Date->
today = date.today()
vlDate.set(today)
# end
# time->
from datetime import datetime
now = datetime.now()
time = now.strftime("%H:%M:%S")
print(time)
vlTime.set(time)
# method for Insertion of vhl rcd
def insertData():
    time=vlTime.get()
    date=vlDate.get()
    vehiclenum=vlNum.get()
    Vinout=vlInout.get()
    Vowner=vlOwner.get()
    Vlmob=vlMob.get()
    vltyp=vlType.get()
    vreason=vlReason.get()
    print("Details:",time,"|",date,"|",vehiclenum,"|",Vinout,"|",Vowner,"|",Vowner,"|",Vlmob,"|",vltyp,"|",vreason)
    VhlReader=open("Data Records/Vehicle.txt","a")
    VhlReader.write(time+"|"+date+"|"+vehiclenum+"|"+Vinout+"|"+Vowner+"|"+Vowner+"|"+Vlmob+"|"+vltyp+"|"+vreason+"\n")
def vehlsearch():
    pass
# checking for textbox
def getname():
    global name
    boxname=name.get()
    print("box 1 entered",boxname)
    exit
name=StringVar()
# 
window.geometry("1493x950")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 950,
    width = 1493,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    273.0,
    183.0,
    image=entry_image_1
)
# date of vhl
vdate = Entry(
    bd=0,
    bg="#C4C4C4",
    highlightthickness=0,
    textvariable=vlDate
)
vdate.place(
    x=182.0,
    y=158.0,
    width=182.0,
    height=48.0
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    515.0,
    260.0,
    image=entry_image_2
)
# mob of vhl
vmob = Entry(
    bd=0,
    bg="#C4C4C4",
    highlightthickness=0,
    textvariable=vlMob
)
vmob.place(
    x=424.0,
    y=235.0,
    width=182.0,
    height=48.0
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    273.0,
    260.0,
    image=entry_image_3
)
# owner name
vhlowner = Entry(
    bd=0,
    bg="#C4C4C4",
    highlightthickness=0,
    textvariable=vlOwner
)
vhlowner.place(
    x=182.0,
    y=235.0,
    width=182.0,
    height=48.0
)

entry_image_4 = PhotoImage(
    file=relative_to_assets("entry_4.png"))
entry_bg_4 = canvas.create_image(
    515.0,
    183.0,
    image=entry_image_4
)
# number of vhtl
vlnum = Entry(
    bd=0,
    bg="#C4C4C4",
    highlightthickness=0,
    textvariable=vlNum
)
vlnum.place(
    x=424.0,
    y=158.0,
    width=182.0,
    height=48.0
)

canvas.create_rectangle(
    9.0,
    0.0,
    1521.0,
    54.0,
    fill="#0F52FF",
    outline="")

canvas.create_text(
    632.0,
    13.0,
    anchor="nw",
    text="SECURITY ASSISTANT ",
    fill="#FFFFFF",
    font=("Inter Bold", 20 * -1)
)

entry_image_5 = PhotoImage(
    file=relative_to_assets("entry_5.png"))
entry_bg_5 = canvas.create_image(
    81.0,
    183.0,
    image=entry_image_5
)
# time
vtime = Entry(
    bd=0,
    bg="#C4C4C4",
    highlightthickness=0,
    textvariable=vlTime
)
vtime.place(
    x=40.0,
    y=158.0,
    width=82.0,
    height=48.0
)

entry_image_6 = PhotoImage(
    file=relative_to_assets("entry_6.png"))
entry_bg_6 = canvas.create_image(
    81.0,
    260.0,
    image=entry_image_6
)
# Mobile of vhl
vlinout = Entry(
    bd=0,
    bg="#C4C4C4",
    highlightthickness=0,
    textvariable=vlInout
)
vlinout.place(
    x=40.0,
    y=235.0,
    width=82.0,
    height=48.0
)
# type of car

entry_image_7 = PhotoImage(
    file=relative_to_assets("entry_7.png"))
entry_bg_7 = canvas.create_image(
    81.0,
    337.0,
    image=entry_image_7
)
vtype= Entry(
    bd=0,
    bg="#C4C4C4",
    highlightthickness=0,
    textvariable=vlType
)
vtype.place(
    x=40.0,
    y=312.0,
    width=82.0,
    height=48.0
)
# Reson Vehile
entry_image_8 = PhotoImage(
    file=relative_to_assets("entry_8.png"))
entry_bg_8 = canvas.create_image(
    273.0,
    337.0,
    image=entry_image_8
)
vhlreason = Entry(
    bd=0,
    bg="#C4C4C4",
    highlightthickness=0,
    textvariable=vlReason
)
vhlreason.place(
    x=182.0,
    y=312.0,
    width=182.0,
    height=48.0
)
# Add Button

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
addbtn = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=insertData,
    relief="flat"
)
addbtn.place(
    x=410.0,
    y=312.0,
    width=210.0,
    height=50.0
)
# Vehicle Record Adding Section Complted

entry_image_9 = PhotoImage(
    file=relative_to_assets("entry_9.png"))
entry_bg_9 = canvas.create_image(
    273.0,
    491.0,
    image=entry_image_9
)
entry_9 = Entry(
    bd=0,
    bg="#C4C4C4",
    highlightthickness=0
)
entry_9.place(
    x=182.0,
    y=466.0,
    width=182.0,
    height=48.0
)

entry_image_10 = PhotoImage(
    file=relative_to_assets("entry_10.png"))
entry_bg_10 = canvas.create_image(
    515.0,
    568.0,
    image=entry_image_10
)
entry_10 = Entry(
    bd=0,
    bg="#C4C4C4",
    highlightthickness=0
)
entry_10.place(
    x=424.0,
    y=543.0,
    width=182.0,
    height=48.0
)

entry_image_11 = PhotoImage(
    file=relative_to_assets("entry_11.png"))
entry_bg_11 = canvas.create_image(
    273.0,
    568.0,
    image=entry_image_11
)
entry_11 = Entry(
    bd=0,
    bg="#C4C4C4",
    highlightthickness=0
)
entry_11.place(
    x=182.0,
    y=543.0,
    width=182.0,
    height=48.0
)

entry_image_12 = PhotoImage(
    file=relative_to_assets("entry_12.png"))
entry_bg_12 = canvas.create_image(
    515.0,
    491.0,
    image=entry_image_12
)
entry_12 = Entry(
    bd=0,
    bg="#C4C4C4",
    highlightthickness=0
)
entry_12.place(
    x=424.0,
    y=466.0,
    width=182.0,
    height=48.0
)

entry_image_13 = PhotoImage(
    file=relative_to_assets("entry_13.png"))
entry_bg_13 = canvas.create_image(
    81.0,
    491.0,
    image=entry_image_13
)
entry_13 = Entry(
    bd=0,
    bg="#C4C4C4",
    highlightthickness=0
)
entry_13.place(
    x=40.0,
    y=466.0,
    width=82.0,
    height=48.0
)

entry_image_14 = PhotoImage(
    file=relative_to_assets("entry_14.png"))
entry_bg_14 = canvas.create_image(
    81.0,
    568.0,
    image=entry_image_14
)
entry_14 = Entry(
    bd=0,
    bg="#C4C4C4",
    highlightthickness=0
)
entry_14.place(
    x=40.0,
    y=543.0,
    width=82.0,
    height=48.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=410.0,
    y=620.0,
    width=210.0,
    height=50.0
)



window.resizable(True,True)
window.mainloop()
